export const UPDATE_MAP_DATA = 'UPDATE_MAP_DATA';
export const UPDATE_ISSUES = 'UPDATE_ISSUES';
export const ADD_NEW_ISSUE = 'ADD_NEW_ISSUE';
// ADD AN ISSUE REDUCER
export const GET_USER_LOCATION = 'GET_USER_LOCATION';
// TOGGLE LOADING REDUCER
export const TOGGLE_LOADING = 'TOGGLE_LOADING';

export const SELECT_ISSUE = 'SELECT_ISSUE';

export const ISSUES_LOADING = 'ISSUES_LOADING';

export const ISSUE_HIGHLIGHTED = 'ISSUE_HIGHLIGHTED';

// ISSUE INPUTS
export const INPUT_ISSUE_TITLE = 'INPUT_ISSUE_TITLE';
export const INPUT_ISSUE_DESCRIPTION = 'INPUT_ISSUE_DESCRIPTION';



// View Issue actions
export const UPDATE_VOTES = 'UPDATE_VOTES';
export const UPVOTE_ISSUE = 'UPVOTE_ISSUE';
export const DOWNVOTE_ISSUE = 'DOWNVOTE_ISSUE';

export const CLEAR_INPUT = 'CLEAR_INPUT';

