export const UPDATE_MAP_DATA = 'UPDATE_MAP_DATA';
export const ADD_NEW_ISSUE = 'ADD_NEW_ISSUE';
// ADD AN ISSUE REDUCER
export const GET_USER_LOCATION = 'GET_USER_LOCATION';
// TOGGLE LOADING REDUCER
export const TOGGLE_LOADING = 'TOGGLE_LOADING';

export const SELECT_ISSUE = 'SELECT_ISSUE';

// ISSUE INPUTS
export const INPUT_ISSUE_TITLE = 'INPUT_ISSUE_TITLE';
export const INPUT_ISSUE_DESCRIPTION = 'INPUT_ISSUE_DESCRIPTION';
